name: 'Synopsys Detect'
description: 'Add SAST and SCA scanning to your GitHub repositories with Synopsys Coverity on Polaris and Black Duck.'
author: 'Gautam Baghel @ Synopsys'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  args:
    description: 'Synopsys Detect arguments'
    required: false
  version:
    description: 'Synopsys Detect version, input 7 or otherwise left empty'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
